apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
data:
  authorized_keys: {{ .Values.pubKey | b64enc | quote  }}
