apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.names.fullname" . }}-crole
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" . }}-sa
    namespace: {{ include "common.names.namespace" . }}

