apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}-crole
rules:
  - apiGroups: ["" ]
    resources: [ "pods", "namespaces"  ]
    verbs: [ "get", "watch", "list", "create", "update", "patch" ]
  - apiGroups: ["apps" ]
    resources: [ "deployments"  ]
    verbs: [ "get", "watch", "list", "create", "update", "patch" ]

